### PR TITLE
Avoid triggering IE's "conditional compilation" feature with sourceURLs

### PR DESCRIPTION
**Pull request by gavacho**
This fixes an issue where minispade'd files don't work in IE8/9.  The who what when where why's of it all are described here: http://www.trdev.co.uk/2011/05/17/ie-gotchas-using-the-coffeescript-plugin-for-requirejs/

### CODE REVIEW

**Comment by hjr3** [comment]
:+1:

**Comment by gavacho** [comment]
I've verified that this doesn't break sourceMap support (tested in chrome) and doesn't cause IE to break because of sourceMap

**Comment by gavacho** [comment]
Is anyone maintaining this project?

**Comment by lukemelia** [comment]
Recent Chrome dev channel builds have deprecated `//@ sourceUrl=` in favor of `//# sourceUrl=`. Any reason not to move this filter to that syntax?

**Comment by gavacho** [comment]
It'd be good to know if IE supports `//#` in addition to `//@`

**Comment by lukemelia** [comment]
Some additional info here: http://updates.html5rocks.com/2013/06/sourceMappingURL-and-sourceURL-syntax-changed

**Comment by lukemelia** [comment]
I think that IE does not support source maps of any kind yet.

**Comment by gavacho** [comment]
IE definitely supports `//@`.  This issue was opened because minispade-produced sourcemaps were braking IE :)

**Comment by jednano** [comment]
Seeing as TypeScript supports them, I'd be surprised if IE doesn't, but it _is_ Microsoft. You never know.

**Comment by lukemelia** [comment]
@gavacho right but IE uses `//@` for conditional comments, not for source maps. @jedhunsaker the articles about TypeScript support all refer to Chrome :)

**Comment by gavacho** [comment]
@lukemelia I think you're right.  I think it _looks_ like there's support because it has some special support for `eval`'d code blocks.

**Comment by jednano** [comment]
"Hopefully either the Visual Studio or IE (or both) team also pick up Source Maps and add support for them too."

http://www.aaron-powell.com/posts/2012-10-03-typescript-source-maps.html

**Comment by lukemelia** [comment]
Moving this discussion to #68

**Pull request merged**
