### PR TITLE
adding es6 module transpiler filter

### PR DESCRIPTION
**Pull request by izhan**
Hi all,

This PR was suggested to me by the friendly Ember folks over at Yapp.  The filter uses Square's ES6 Module Transpiler (https://github.com/square/es6-module-transpiler) through a Ruby gem I created (https://github.com/izhan/ruby_es6_module_transpiler).  The gem is modeled closely after a Rails gem (https://github.com/izhan/es6_module_transpiler-rails) and will continue to be improved in the future.  For an example of the filter in action, see https://github.com/izhan/rake-pipeline-tester.

I am open to suggestions for improving both this PR as well as the Ruby gem.

Thanks

### CODE REVIEW

**Comment by hjr3** [comment]
:+1:

**Comment by hjr3** [comment]
Leaving this open for a few more days to let people comment. Will merge at 7 days if no one has any concerns.

**Comment by izhan** [comment]
@hjr3 Thanks for the followup -- sounds good.  I will continue updating the PR for any bugs or improvements I find.

**Comment by lukemelia** [comment]
@izhan can you provide an example in the testing app of setting the moduleName?

**Comment by lukemelia** [comment]
@izhan it would be convenient to document the available options for the filter in this project, or provide a link to such documentation for the transpiler.

**Comment by izhan** [comment]
Updated branch with PR from @yappbox that created a module_id_generator option.  Will definitely add documentation and examples -- expect it in the next few days

**Comment by hjr3** [comment]
:+1:

**Comment by izhan** [comment]
apologies for the late followup.  PR has been updated to include an "available options" link within the readme.  I also updated the testing app on the other repo to include an example of setting the moduleName.

Is this PR good to go?

**Pull request merged**
